version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch85
    environment:
      - cluster.name=es-cluster-85
    volumes:
      - ./esdata85:/usr/share/elasticsearch/data
    #  - ./elasticsearch-es2-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      elastic85:
      elasticsearch_network:
        ipv4_address: 172.20.0.2 
  kibana_85:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana85
    #environment:
    ports:
      - 5601:5601
    networks:
      elastic85:
      elasticsearch_network:
        ipv4_address: 172.20.0.3
    volumes:
      - ./kdata85:/usr/share/kibana/data
      - ./kibana-local.key:/usr/share/kibana/config/kibana-local.key
      - ./kibana-local.crt:/usr/share/kibana/config/kibana-local.crt
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  elastic85:  
  elasticsearch_network:  
    external: true

volumes:
  esdata85:
  kdata85: